```
set compatible
color desert
set  t_Co=256

syntax on                                                                                                                                                                     
set showmatch       " Marcar matching brackets                                                                                                                               
set smarttab        " Auto tabs
set showcmd             " Show (partial) command in status line.
set ignorecase          " Ignora case sensitive
set smartcase           " Do smart case matching
set incsearch           " Incremental search

" Utilizar vimrc global
if filereadable("/etc/vim/vimrc.local")
    source /etc/vim/vimrc.local
endif

" Archivo actual
set ruler
set laststatus=2

" Highlight linea actual
set cursorline
highlight CursorLine ctermbg=Black term=bold cterm=bold

" Tab = 4 spaces
set ts=4 sw=4

```
